# Where things are
source: ./src
destination: ./distrib
plugins_dir: ./plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
includes_dir: _includes
data_dir: _data
sass:
  sass_dir: ./src/_sass

# Handling Reading
safe: false
include: [ ".htaccess", ".htpasswd" ]
exclude: [ "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "README.md", "*.section.md", "*.less" ]
keep_files: [ "index.html" ]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false
disable_disk_cache: true

# scoping
defaults:
  - scope:
      path: "index.md" # landing page
    values:
      lang: "en"
      layout: plain
      is_home: false
      in_menu_popup: false
      in_menu_topbar: false
      in_menu_footer: false
      render_this: true
      absolute_paths: false
      in_shortcuts: false
  - scope:
      path: "error"
    values:
      lang: "en"
      layout: plain
      is_home: false
      in_menu_popup: false
      in_menu_topbar: false
      in_menu_footer: false
      render_this: true
      absolute_paths: false
      in_shortcuts: false